text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: ../bin
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
    config:
      allow_periods_in_identifiers: true
watcher:
  dirs_to_watch: [ 'content', 'layouts', 'lib' ]
  files_to_watch: [ 'config.yaml', 'Rules' ]

  notify_on_compilation_success: true
  notify_on_compilation_failure: true
